spring:
  application:
    name: expense_tracker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver

    # Supabase
#    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
#    username: postgres.eqgclhodynrgjbwijznz
#    password: 093606872Tanghai$
#
    #Work
    url: jdbc:postgresql://localhost:5432/configure
    username: postgres
    password: 309927605

    #Personal
#    url: jdbc:postgresql://localhost:5432/merchant
#    username: postgres
#    password: admin

telegram:
  bot-token: 6146637472:AAEF3MsqfUsFD4PXc81Ro4tYpiNyu4ajwQI
  chat-id: 678134373

server:
  servlet:
    context-path: /exp_tkr
  port: 8080
