spring:
  application:
    name: expense_tracker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver

    # Supabase
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    #Work
#    url: jdbc:postgresql://localhost:5432/configure
#    username: postgres
#    password: 309927605

    #Personal
#    url: jdbc:postgresql://localhost:5432/merchant
#    username: postgres
#    password: admin

telegram:
  enable: ${TELEGRAM_BOT_ENABLE}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

server:
  servlet:
    context-path: /expense_tracker
  port: 8080
