spring:
#  profiles:
#    active: local
  application:
    name: expense_tracker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    # Supabase
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: ${JPA_VIEW_MODE}

render:
  web_url: ${SERVER_UR}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  auth:
    users:
      admin_usr: ${ADMIN_USERNAME}
      admin_pwd: ${ADMIN_PASSWORD}

telegram:
  enable: ${TELEGRAM_BOT_ENABLE}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

server:
  servlet:
    context-path: /expense_tracker
  port: 8080
